### ISSUE TITLE
Where does `doneSsrAttach` come from?

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs-streaming-product-page#8]
Where does `doneSsrAttach` come from here: https://github.com/donejs/donejs-streaming-product-page/blob/160bfe17743d39de4bb6ec6b193a59827f75f673/src/index.js#L98

Also, are zones being used in the client so `document` on this line:

https://github.com/donejs/donejs-streaming-product-page/blob/160bfe17743d39de4bb6ec6b193a59827f75f673/src/index.js#L12

is referring to `var doc = document.implementation.createHTMLDocument();`?

If this is the case, does `renderApp` really even need to take a `document` as an argument?

**Comment by justinbmeyer** [comment]
if there's going to be a `zone` and some sort of `ssrAttach` method, we should probably create something that links these together:

```js
if(!isNode){
  doneSSRRenderThenAttach(renderApp)
}
```

Btw, is the response object passed somehow to all of this so 404s can work?

**Comment by matthewp** [comment]
`doneSsrAttach` is a global provided by done-ssr-incremental-rendering-client. It allows that library to decide when it should *swap* out the page's HTML for the fragment. Internally done-autorender knows to call this function if it exists as a global.

Making this user-friendly is hard, because the intention is that you should not need to change your code to use incremental rendering.
